name: CI & Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'         # v0.1.0, v1.2.3 등
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    # 태그(push tag) 이벤트일 땐 건너뜁니다
    if: github.event_name != 'push' || github.ref_type != 'tag'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Debug build
        run: cargo build

      - name: Release build
        run: cargo build --release

      - name: List artifacts
        run: ls -l target/{debug,release}

  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    if: github.event_name != 'push' || github.ref_type != 'tag'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Debug build
        run: cargo build

      - name: Release build
        run: cargo build --release

      - name: List artifacts
        shell: bash
        run: ls -l target/release

  release:
    name: Create GitHub Release
    needs:
      - build-linux
      - build-windows
    runs-on: ubuntu-latest
    # 오직 태그 푸시일 때만 실행
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Release build
        run: cargo build --release

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload shared library (.so)
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/release/libread_ahtx0_rs.so
          asset_name: libread_ahtx0_rs.so
          asset_content_type: application/octet-stream

      - name: Upload versioned symlink (.so.${{ github.ref_name }})
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/release/libread_ahtx0_rs.so.${{ github.ref_name }}
          asset_name: libread_ahtx0_rs.so.${{ github.ref_name }}
          asset_content_type: application/octet-stream

      - name: Upload CLI binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/release/read_ahtx0_cli
          asset_name: read_ahtx0_cli
          asset_content_type: application/octet-stream
