# .github/workflows/release.yml
name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # 예: v0.1.0, v1.2.3 등 태그 푸시 시 트리거

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Release
        run: cargo build --release

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}       # 푸시된 태그 (예: v0.1.0)
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload shared library (.so)
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/release/libread_ahtx0_rs.so
          asset_name: libread_ahtx0_rs.so
          asset_content_type: application/octet-stream

      - name: Upload versioned symlink (.so.<ver>)
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/release/libread_ahtx0_rs.so.${{ github.ref_name#v }}
          asset_name: libread_ahtx0_rs.so.${{ github.ref_name#v }}
          asset_content_type: application/octet-stream

      - name: Upload CLI binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/release/read_ahtx0_cli
          asset_name: read_ahtx0_cli
          asset_content_type: application/octet-stream
